# -*- coding: utf-8 -*-
"""ImageScraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1whZAP7uEnxIBDIWEq_76fYxBE9-DqSJU
"""

!pip install google_images_download
from google.colab import drive
drive.mount('/content/gdrive')
!pip install -U -q PyDrive ## you will have install for every colab session
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
import matplotlib.pyplot as plt
# %matplotlib inline

!wget https://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip  && unzip chromedriver_linux64

colab_path = '/gdrive/../content/'
chromedriver_path = '/gdrive/../content/chromedriver'

root = '/content/gdrive/My Drive/'
!ls '/content/gdrive/My Drive/'

from google_images_download import google_images_download  

keyws   = "cwd deer"
limit   = 50
chromedriver = chromedriver_path
offset  = None  
color_type	= None
size    = None 
usage_rights	= None 

arguments = {
        "keywords" : keyws,
        "limit" :limit,
        "chromedriver":chromedriver,
        "offset" : offset,
        "color_type" : color_type,
        "size" : size,
        "usage_rights" : usage_rights
        }   
response  = google_images_download.googleimagesdownload()   
response.download(arguments)

dataset_path = 'downloads/' + keyws + '/'
dataset = [ dataset_path + img_name for img_name in drive._os.listdir( colab_path + dataset_path ) ]

img =plt.imread( dataset[0] )
plt.imshow( img)
